### ISSUE TITLE
Seed Storage not available

### ISSUE THREAD

**Issue by DAmNRelentless** [AgriCraft/AgriCraft#1190] opened 2018-09-25 03:18 UTC
## Quick description
Although the seed storage system is enabled in the config, the seed storage does not show up in JEI nor can I find it anywhere else.

## Related issues and searches
-/-

## Mods and versions used
* Minecraft: 1.12.2
* AgriCraft: 2.12.0-1.12.0-a6
* InfinityLib: 1.12.0

## Steps to replicate the issue
-/-

## Expectations and explanations
Normally there are seed storages where you can put seeds in but you don't get any recipe, nor is the item existant in creative mode.

## Your environment
* How are you playing?
  * Operating System: W10
  * Launcher: Twitch
  * Modpack: Custom, also tried Vanilla with only agricraft
* What kind of server:
  * [x] Singleplayer
  * [x] Multiplayer
* Game Modes:
  * [x] Survival
  * [x] Creative
* Save File:
  * [x] Brand new save
  * [x] Only an existing save

## Links to crash logs, stack traces, etc
-/-

## Screenshots (or videos)
-/-

**Comment by JFMillerUSA** [comment] 2019-06-24 19:58
Any answers please, almost been a year

**Comment by darthvader45** [comment] 2019-06-30 21:46
Can you try crafting it?  If it's still craftable, they may have just not added compat for it yet.

**Comment by RlonRyan** [comment] 2019-07-27 22:40
Duplicate of issue #43

Unfortunately the seed storage is a relatively complicated feature of AgriCraft, which we have not had the time to add back in given other issues.

**Closed by RlonRyan** 2019-07-27 22:40 UTC
Labels: duplicate

**Comment by knightrum** [comment] 2020-03-08 08:01
year later?
