### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by vrork** [AgriCraft/AgriCraft#996] opened 2017-06-08 13:35 UTC
Agricraft 2.0.0-0.10.0-a18, Minecraft 1.10.2

https://gist.github.com/vrork/cbac30cc5897bb34f2e857336fe75276

**Comment by WhiskersWatson** [comment] 2017-06-08 19:40
Can confirm, just got the same error after trying to agricraft to my pack https://pastebin.com/d66Qyvua

**Comment by Jacky1356400** [comment] 2017-06-09 11:16
Same here. Updated AgriCraft to a18 and it started to crash on startup. [Crash Report](https://pastebin.com/XstizsnX)

**Comment by RlonRyan** [comment] 2017-06-12 18:16
Duplicate of #987

**Closed by RlonRyan** 2017-06-12 18:16 UTC
