### ISSUE TITLE
No botania seeds altough they are enabled

### ISSUE THREAD

**Issue by MayusYT** [AgriCraft/AgriCraft#1222] opened 2019-04-27 08:12 UTC
I'm currently creating a SkyFactory 4 Remix that includes both AgriCraft and Botania.
I want to make it possible to use AgriCraft in order to obtain the Botania flowers. I wanted to enable those recipes in the config, but apparently they are already enabled:
```json
{
  "path": "mod_Botania/plants/botania_brown_plant.json",
  "enabled": true, 
  "id": "botania:brown_flower_plant",
  "plant_name": "Mystical Brown Flower",
  "seed_name": "Mystical Brown Seeds",
  "seed_items": [],
  "description": {
    "translations": {},
    "default": "A beautiful flower that is as brown as the dirt."
  },
  "growth_chance": 0.75,
  "growth_bonus": 0.025,
  "bonemeal": false,
  "tier": 1,
  "weedable": false,
  "aggressive": false,
  "spread_chance": 0.1,
  "spawn_chance": 0.0,
  "grass_drop_chance": 0.0,
  "seed_drop_chance": 1.0,
  "seed_drop_bonus": 0.0,
```
What else could I do in order to enable the crafting of botania plants?

**Comment by MayusYT** [comment] 2019-04-27 08:19
This, for example, is the botania_white_mutation.json file:
```json
{
  "path": "mod_Botania/mutations/botania_white_mutation.json",
  "enabled": true,
  "chance": 0.5,
  "child": "botania:white_flower_plant",
  "parent1": "wheat_plant",
  "parent2": "melon_plant"
}

```
As you can tell, it's enabled, but JEI doesn't show the recipe.

**Comment by Vislor** [comment] 2019-05-18 00:22
The issue is the capital 'B' in the folder name.  You need to change that to mod_botania (lowercase b): both the actual folder name as well as the path entries inside the various json files.

**Comment by Khroz** [comment] 2019-05-19 07:19
I tried that and it only creates another folder with json files and the capital B again.

![imagen](https://user-images.githubusercontent.com/50791774/57978981-6f627400-79dc-11e9-9844-bc9ca58f6c16.png)

**Comment by darthvader45** [comment] 2019-05-19 15:47
If that's the case, then it might be a problem with the compatibility part of the mod.  Can someone check the code that generates the folders?

**Comment by Khroz** [comment] 2019-05-19 16:23
I would like to try but looked in the code yesterday and sincerely don't know where to search for that, if someone could help pointing out where that would be great.

**Comment by Vislor** [comment] 2019-05-19 18:42
Once I added the lowercase folder it also regenerated the folder with the capital letter on my server as well, to be honest this would be expected, on Linux at least.  Since Linux is a case-sensitive file system the default initialization code would be looking for the capital letter version and not seeing it would create it again.

It is possible that if the client isn't corrected as well that loading the defaults on the client is messing up the server's sent configuration.  There are actually 4 mutations that are incorrect in the Botania JSON files (yellow, cyan, white, and gray if I remember correctly), and even though I fixed those on the server (you need to add the prefix "vanilla:" inside the mutation JSON files) the mutations still didn't show up on the client.  

I had to correct those in the client's default config before the client recognized them (even though the server-sent ones are supposed to override the client.)  I guess when the client encountered an error loading those then it turned them off permanently.

**Comment by Vislor** [comment] 2019-05-19 18:55
> If that's the case, then it might be a problem with the compatibility part of the mod. Can someone check the code that generates the folders?

It looks like the default JSON is imported from the Agricraft/AgriPlants repo during the build process.  There is an open pull request in that repo to fix this issue, but it hasn't been merged or acknowledged as of yet.

**Comment by Khroz** [comment] 2019-05-19 21:55
> 
> It looks like the default JSON is imported from the Agricraft/AgriPlants repo during the build process. There is an open pull request in that repo to fix this issue, but it hasn't been merged or acknowledged as of yet.

Everything Vislor is saying is correct. It's working now, it needs to be done on client side too so the server "synchs" with those files and stops asking for the wrong ones. I can see them now inside NEI in my server and i'm testing if it'll crossbreed, also podzol now accepts crop sticks so i'm guessing it will.

Finally, yeah the AgriPlants repo is where it's wrong and yep the pull request has not been merged yet. Thanks for helping on this one friends i love y'all and i hope it gets fixed soon.

**Closed** 2019-08-07 06:20 UTC
Labels: json
