### ISSUE TITLE
Ticking entity/block update crash

### ISSUE THREAD

**Issue by CloWnicide** [AgriCraft/AgriCraft#1165] opened 2018-07-08 04:19 UTC
Seems to be an issue that originated from Actually Additions worms on the same block as a crop, and now the entire area is being ticked upon loading the world. Trying to remove the blocks and entities through MC Edit, but here is the crash report.

<details>
<summary> Click to expand. </summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b150.jar)
  LibLoader (# LibLoader.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  RandomPatches (randompatches-1.12.2-1.1.0.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  EECore (ExpandedEquivalence-1.12.2-4r.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  CoreMod (TickProfiler-1.12-0.0.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.16-99.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  AstralCore (astralsorcery-1.12.2-1.9.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.17.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.9.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  ISCore (ImprovableSkills_1.12.2-3.4.1r.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-80.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.3.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.8-core.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 7/7/18 9:07 PM
Description: Exception while updating neighbours

java.lang.NoClassDefFoundError: jline/internal/Preconditions
	at com.infinityraider.agricraft.api.v1.soil.IAgriSoil.isVarient(IAgriSoil.java:42)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry.lambda$contains$0(AgriSoilRegistry.java:36)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry$$Lambda$6140/1318104033.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.tryAdvance(ConcurrentHashMap.java:3574)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry.contains(AgriSoilRegistry.java:36)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry$$Lambda$6139/858511666.test(Unknown Source)
	at java.util.Optional.filter(Optional.java:178)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry.contains(AgriSoilRegistry.java:23)
	at com.infinityraider.agricraft.blocks.BlockCrop.canBlockStay(BlockCrop.java:349)
	at com.infinityraider.agricraft.blocks.BlockCrop.observedNeighborChange(BlockCrop.java:336)
	at net.minecraft.world.World.func_190529_b(World.java:586)
	at net.minecraft.world.World.func_190522_c(World.java:481)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:389)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at net.minecraft.block.BlockFarmland.func_180650_b(BlockFarmland.java:60)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: jline.internal.Preconditions
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.infinityraider.agricraft.api.v1.soil.IAgriSoil.isVarient(IAgriSoil.java:42)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry.lambda$contains$0(AgriSoilRegistry.java:36)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry$$Lambda$6140/1318104033.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.tryAdvance(ConcurrentHashMap.java:3574)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry.contains(AgriSoilRegistry.java:36)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry$$Lambda$6139/858511666.test(Unknown Source)
	at java.util.Optional.filter(Optional.java:178)
	at com.infinityraider.agricraft.impl.v1.AgriSoilRegistry.contains(AgriSoilRegistry.java:23)
	at com.infinityraider.agricraft.blocks.BlockCrop.canBlockStay(BlockCrop.java:349)
	at com.infinityraider.agricraft.blocks.BlockCrop.observedNeighborChange(BlockCrop.java:336)

-- Block being updated --
Details:
	Source block type: ID #60 (tile.farmland // net.minecraft.block.BlockFarmland)
	Block: agricraft:crop
	Block location: World: (237,72,-273), Chunk: (at 13,4,15 in 14,-18; contains blocks 224,0,-288 to 239,255,-273), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.World.func_190529_b(World.java:586)
	at net.minecraft.world.World.func_190522_c(World.java:481)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:389)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at net.minecraft.block.BlockFarmland.func_180650_b(BlockFarmland.java:60)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: Let It End
	All players: 1 total; [EntityPlayerMP['Matricide'/947, l='Let It End', x=256.48, y=2.00, z=-203.47]]
	Chunk stats: ServerChunkCache: 681 Drop: 0
	Level seed: -5416655493079973942
	Level generator: ID 09 - lostcities, ver 0. Features enabled: true
	Level generator options: { "profile": "rarecities" }
	Level spawn location: World: (138,64,472), Chunk: (at 10,4,8 in 8,29; contains blocks 128,0,464 to 143,255,479), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3144867 game time, 3154885 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 99824 (now: false), thunder time: 9250 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
</details>

**Comment by TehNut** [comment] 2018-07-08 04:29
#1152

**Comment by CloWnicide** [comment] 2018-07-08 04:35
Thanks for explaining nothing and just posting another issue's number, but I am able to put crops down and everything was working fine even with the worms on the same block, so you've literally just posted something useless.

**Comment by TehNut** [comment] 2018-07-08 04:40
Thanks for not bothering to read the linked PR that fixes the exact issue you're having.

**Comment by CloWnicide** [comment] 2018-07-08 04:45
Sorry for not understand how to fix someone else's code, but I don't know enough on how to do it anyways, so again that was useless for me. Thanks again.

**Comment by darthvader45** [comment] 2018-07-08 15:16
Are we done?  Anyways, good to see someone re-added
jline.internal.Preconditions, so this won't happen again.

Golden rule in Minecraft: Never dig straight down.

**Comment by RlonRyan** [comment] 2018-07-10 04:19
Duplicate of #1152.

**Closed by RlonRyan** 2018-07-10 04:19 UTC
