### ISSUE TITLE
Agricraft seems to be the problem with my game

### ISSUE THREAD

**Issue by Lewis1206** [AgriCraft/AgriCraft#1161] opened 2018-07-04 21:03 UTC
## Quick description
 I was playing Modern Skyblock 3 and then all of a sudden my game wouldent load when i loaded it up i checked everything was up to date and it was. I went on reddit first and posted about this. It freezes as soon as my world loads up. I got a response on reddit and a guy looked through my crash logs and told me to come here after thinking this mod was the issue. I downgraded the mod and that didnt help. This is what he said to me. In your crash report, it looks like when it checked if IAgriSoil.java:42 was a variant (for some reason the method was called isVarient, not isVariant ???) of its soil and it returned null instead of true or false. That's why I believe it may be a specific block of some sort. The error primarily happened on the Serverside.

## Mods and versions used

Modern skyblock 3
Agricraft 2.12.0-1.12.0-a4

## Steps to replicate the issue

1. Load up world
2. Game freezes instantly without loading in the world

## Your environment

* How are you playing?
  * Operating System: Windows 10 64 bit
  * Launcher: Twitch Launcher
  * Modpack: Modern skyblock 3
* What kind of server:
  * [ X] Singleplayer
  * [ ] Multiplayer
* Game Modes:
  * [X ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [X ] Only an existing save

## Links to crash logs, stack traces, etc

https://pastebin.com/KWmYRgJQ 
https://pastebin.com/FXQFhi0k 
https://pastebin.com/C79fJ0g9

**Comment by TehNut** [comment] 2018-07-04 22:10
This was fixed by #1152

**Comment by RlonRyan** [comment] 2018-07-10 04:20
Duplicate of #1152

**Closed by RlonRyan** 2018-07-10 04:20 UTC
