### ISSUE TITLE
Server crash when loading a existing world

### ISSUE THREAD

**Issue by scalda** [AgriCraft/AgriCraft#995] opened 2017-06-08 07:31 UTC
Hi, 

So I released Foolcraft 1.4 beta yesterday, went to start the update process on all of iskall85's patreons servers and the first server I update and started, it started throwing the crash log below?

latest version
agricraft-2.0.0-0.10.0-a18.jar
infinitylib-0.10.0.jar

[crashlog](https://pastebin.com/jPr1va6s)

regards

Scalda
(FoolCraft Modpack Dev)

**Comment by scalda** [comment] 2017-06-08 07:49
#987

**Comment by RlonRyan** [comment] 2017-06-12 18:17
Duplicate of #987.

**Closed by RlonRyan** 2017-06-12 18:17 UTC
