### ISSUE TITLE
Irrigation sprinklers dont work

### ISSUE THREAD

**Issue by nak0604** [AgriCraft/AgriCraft#1078] opened 2017-10-06 07:06 UTC
Running a modpack with agricraft 2.0.0-0.10.0-a19 and minecraft 1.10.2 and irrigation sprinklers wont irrigate the tilled dirt blocks.

**Comment by darthvader45** [comment] 2017-10-06 17:58
They currently irrigate at the origin 0,0,0 and above the sprinkler.  Try going to the Agricraft Discord server and download a21.

**Comment by CodesCubesAndCrashes** [comment] 2017-10-15 11:18
Duplicate of #862. But the fix is in testing!

**Closed by CodesCubesAndCrashes** 2017-10-15 11:18 UTC
