### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by CamaroKing59** [AgriCraft/AgriCraft#1003] opened 2017-06-12 13:12 UTC
https://pastebin.com/qPE5z28h

Agricraft Version: 2.0.0-0.10.0-a18
Minecraft version: 1.10.2
Forge Verison: 12.18.3.2316

**Comment by RlonRyan** [comment] 2017-06-12 18:10
Duplicate of #987.

**Closed by RlonRyan** 2017-06-12 18:10 UTC
