### ISSUE TITLE
Invasive Chat Message

### ISSUE THREAD

**Issue by Boolyman** [AgriCraft/AgriCraft#1236] opened 2019-08-06 19:38 UTC
Is there any way to get rid of the invasive  multi-line agricraft alpha message when players join the world?  200 mods in the pack, but only Agricraft takes special privilege to hijack the chat screen with their own dedicated text.  Funny or serious message doesnt matter.  We have things we want in that box as pack devs and server admins.  The normal players of our packs don't care about the alpha status of one of the hundreds of mods in the pack... especially every  single time they log in.  It breaks immersion, its been around for as long as I can remember, and serves no purpose, especially after the first 30 times it's shown.

**Comment by jolandepoel** [comment] 2019-09-19 10:00
I wondered about and searched for the same thing. It's a dev choice, and according to the conversation in the referenced issue, they are never going to change it. 

Duplicate of #889

**Comment by jolandepoel** [comment] 2019-10-02 10:12
You can, however, change it to a one line message by enabling 'use boring alpha warning message' in the config.

**Comment by iamtechi27** [comment] 2019-10-21 02:00
Bump. The message is incredibly invasive, even if only the one liner. Imagine if every mod author thought they were so special as to spam chat every time I join a world. Things would get annoying real quick. I'm playing a large pack and you aren't the only mod that's in "alpha", knock it off.

**Comment by Boolyman** [comment] 2019-10-21 05:18
Not to mention, the same Alpha warning has been in the mod for (a) year(s) or more.  Its a bit ridiculous... and if they are as diligent about bringing it out of Alpha, as they are about responding to these issue trackers... the mod will never be finished.

**Comment by InfinityRaider** [comment] 2021-01-22 22:01
"The mod will never be finished"

There is truth in that statement, I recommend to manage your expectations related to hobby projects.

**Closed by InfinityRaider** 2021-01-22 22:01 UTC
Labels: wontfix
