### ISSUE TITLE
[1.12.2]Sprinkler doesnt work and wrong placement

### ISSUE THREAD

**Issue by xILikepuddingx** [AgriCraft/AgriCraft#1122] opened 2018-04-09 05:28 UTC
## Quick description
Sprinklers do not work. There is water in the channels and it is connected, but it does not work. In addition, you can not grow 3x3 sprinklers, because they, if they were placed next to each other, break down independently.

## Mods and versions used

* Minecraft: 1.12.2
* AgriCraft: agricraft-2.12.0-1.12.0-a3
* InfinityLib: infinitylib-1.12.0
* there is to much mods for a list. i use the modpack modern skyblock 3.

## Steps to replicate the issue
See video below

## Expectations and explanations
they work

## Your environment

* How are you playing?
  * Operating System: Windows 10 64 Bit
  * Launcher: MyFTB Launcher
  * Modpack: Modern Skyblock 3
* What kind of server:
  * [ ] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [ ] Brand new save
  * [ ] Only an existing save

## Screenshots (or videos)
https://files.ilikepudding.tk/wt2o014kh1.mp4

**Comment by cowboyfunk** [comment] 2018-04-12 09:54
I'd also add that you can't put sprinklers on the solid version of irrigation channels at all, modpack Modern Skyblock 3 v.3.3.1

**Comment by RlonRyan** [comment] 2018-04-14 00:44
Duplicate of closed issue.

**Closed by RlonRyan** 2018-04-14 00:44 UTC
