### ISSUE TITLE
Launching Crash

### ISSUE THREAD

**Issue by PhilSkinn** [AgriCraft/AgriCraft#1075] opened 2017-09-21 04:17 UTC
I have been having an issue whenever I install EnderIO(1.7.10-2.3.0.429_beta), EnderIO Addons(1.7.10-2.3.0.427_beta-0.10.11.54), and Agricraft(1.7.10-1.5.0). The crash report comes back and it seems like it may be something wrong with an Agricraft Class. The crash report is as follows:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 9/20/17 11:17 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/InfinityRaider/AgriCraft/blocks/BlockCrop
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/InfinityRaider/AgriCraft/blocks/BlockCrop
	at com.InfinityRaider.AgriCraft.AgriCraft.preInit(AgriCraft.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.InfinityRaider.AgriCraft.blocks.BlockCrop
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.lang.NoClassDefFoundError: net/shadowmage/ancientwarfare/api/IAncientWarfareFarmable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 39 more
Caused by: java.lang.ClassNotFoundException: net.shadowmage.ancientwarfare.api.IAncientWarfareFarmable
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
-----------------------------------------------------------------------------------------------------------
I left out all the successfully initialized mods...
The errored mods are:
- UCE	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar)
- UCE	RedstoneArsenal{1.7.10R1.1.3B1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.3B1-94.jar)
- UCE	RArm{1.7.10-1.2.0-41} [Redstone Armory] (RedstoneArmory-1.7.10-1.2.0-41.jar)

**NOTE**   The mods failed to load, even when I didn't have Redstone Arsenal and Redstone Armory installed and returned with basically the same thing. 

I will also include a list of the mods that I have installed because it _might_ help with diagnosing and solving the problem. 

- AE2Stuff(0.5.0.56-mc1.7.10)
- Agricraft(1.7.10-1.5.0)
- AncientTrees(1.7.10-1.6.4)
- AncientWarfare(2.4.104-beta-MC1.7.10-FULL)
- AppliedEnergistics2(rv3-beta-6)
- Aroma1997Core(1.7.10-1.0.2.16)
- AromaBackup(1.7.10-0.0.0.5)
- Artifice(1.7.10-1.1.5R-399)
- AsieLib(1.7.10)
- bdlib(1.9.2.104-mc1.7.10)
- BloodMagic(1.7.10-1.3.1-7)
- buildcraft(7.1.22)
- Chisel(2.9.5.11)
- CodeChickenCore(1.7.10-1.0.7.47)
- CoFH(1.7.10-3.1.4-329)
- ComputerCraft(1.74)
- Enchiridion(2-1.7.10-2.0.2a)
- EnderCore(1.7.10-0.2.0.36_beta)
- EnderIO(1.7.10-2.3.0.429_beta)
- EnderIOAddons(1.7.10-2.3.0.427_beta-0.10.11.54_beta)
- EwysWorkshop(1.1.2)
- Ex-Astris(MC1.7.10-1.16-36)
- Ex-Nihilo(1.38-36)
- ExtraTiC(1.7.10-1.4.5)
- ExtraUtilities(1.2.11)
- iChunUtil(4.2.2)
- ImmersiveEngineering(0.7.7)
- JourneyMap(5.0.1_Unlimited_MC1.7.10)
- KoreSample(1.7.10-1.3.2)
- MagicalCrops(4.0.0_PublicBeta3)
- MagicalCropsArmory(4.0.0_PublicBeta4)
- MagicalCropsDeco(4.0.0_PublicBeta4a)
- Mantle(1.7.10-0.3.2)
- MaricultureDeluxe(1.7.10-1.3.0-6)
- Mekanism[Generators/Tools/Core](1.7.10-8.1.7.252)
- Metallurgy(1.7.10-4.0.9.148)
- MetallurgyCore(1.7.10-4.0.5.30)
- MineFactoryReloaded(1.7.10-2.8.1-174)
- NotEnoughItems(1.7.10-1.0.5.120-universal)
- Optifine(1.7.10_HD_U_D8)
- OreExcavation(1.1.101)
- RanchableFluidCows(Beta-1.7.10-1.1.1)
- RandomThingsMod(1.7.10)
- RedstoneArmory(1.7.10-1.2.0-41)
- RedstoneArsenal(1.7.10-1.1.3B1-94)
- StatuesMod(1.7.10)
- Storage Drawers(1.7.10-1.7.0)
- SyncMod(1.7.10)
- TConstruct(1.7.10-1.8.5)
- Thaumcraft(1.7.10-4.2.3.5)
- ThaumicEnergistics(1.0.0.5)
- ThaumicExploration(1.7.10-1.1-37)
- ThaumicTinkerer(2.5-1.7.10-502)
- ThermalExpansion(1.7.10-4.1.5-37)
- ThermalFoundation(1.7.10-1.2.6-188)
- ThermalSmeltery(1.3.1.4)
- TiCTooltips(mc1.7.10-1.2.3)
- Waila(1.5.10_1.7.10)
- WailaHarvestability(mc1.7.x-1.1.2)

(Basically Guaranteeing that I've misspelled something here)

If this crash has happened before in the issues forum, please let me know so I can delete this post.

**Comment by PhilSkinn** [comment] 2017-09-21 04:22
I'll delete the config file and see if it does anything. Just not right now.

**Comment by CodesCubesAndCrashes** [comment] 2017-09-21 08:02
I'll take a peek at this, but full disclosure: the 1.7.10 version isn't getting updates any more. Fingers crossed, maybe there's a known solution already.

**Comment by CodesCubesAndCrashes** [comment] 2017-10-15 11:59
@PhilSkinn Any updates? I don't want to just close this because it's for an old version. It would be better to at least narrow down what the bug is, if possible. 

Taking another look at the trace, I noticed that the ultimate cause of the error is possibly actually **Ancient Warefare 2**. Stack traces are funny, they're kinda backwards. You have to look at the last 'chunk' to find the top of it. 

    Caused by: java.lang.ClassNotFoundException: 
    net.shadowmage.ancientwarfare.api.IAncientWarfareFarmable
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 43 more

We can look up that file (**[api/IAncientWarfareFarmable.java](https://github.com/shadowmage45/AncientWarfare2/blob/1.12.x/src/main/java/net/shadowmage/ancientwarfare/api/IAncientWarfareFarmable.java)**), and see that it is doing something with the `IGrowable` interface from vanilla. 

#### May I suggest: 
* Testing things out after removing Ancient Warfare 2.
* And **[definitely updating](https://minecraft.curseforge.com/projects/ancient-warfare-2/files)** it from **2.4.104** (Beta, May 2015) to **2.4.115** (Release, March 2016).

## Addendum: 
Looking even more closely, we find [an entire pull request](https://github.com/shadowmage45/AncientWarfare2/pull/374) fixing things up, submitted by *none-other-than the one and only InfinityRaider*! :grin: And that's included in build 111 (August 2015), so it was fixed after 2.4.104 came out.

**Closed** 2017-10-28 02:39 UTC
Labels: Awaiting reply, invalid, other mod

**Comment by CodesCubesAndCrashes** [comment] 2017-10-28 02:41
If there's any more on this, I'll still get an email and be able to follow up. The issue itself I'm going to close because I think it's unlikely someone will have this exact same configuration.
