### ISSUE TITLE
Seeds Won't Drop From Wheat or Potatoes

### ISSUE THREAD

**Issue by bcrotty** [AgriCraft/AgriCraft#1072] opened 2017-09-16 23:19 UTC
Wheat and potatoes will spread to neighboring crop sticks, but when I break the newly spread seeds by left clicking, I just get the crop sticks back. I am using the AgriCraft crop sticks, and this is version agricraft-2.0.0-0.10.0-a17 in FTB Beyond. I haven't tried with other crops yet.

**Comment by CodesCubesAndCrashes** [comment] 2017-09-16 23:41
Heads up: a17 is a few versions behind. You can find a19 on [CurseForge](https://minecraft.curseforge.com/projects/agricraft/files/2442940). Please try updating first. 

That said, I don't remember that bug, and I don't see it mentioned in any commit or the changelog. So I can't promise it'll be fixed by updating. 

There are two other possibilities I can think of: 1) it got fixed under the hood during the general rewrite. Or 2) the JSONs for those plants could be different from the defaults. Please confirm that the seed drop chances are non-zero?

**Comment by bcrotty** [comment] 2017-09-17 01:16
Upgrading fixed the seed problem, but now I can't seem to get any stat increases. Also, the water tank doesn't show when it has water in it. Any ideas on those? Want me to create separate issues?

**Comment by CodesCubesAndCrashes** [comment] 2017-09-17 01:33
Glad to hear the original bug is gone. :) 

The stat problem has an open issue already, and a fix has been written too. There should be a (genuinely soon) new release which includes it. 

Can you elaborate on the tank issue? Do you mean the water isn't visible in the model, or in WAILA, or something else? What are the steps to reproduce the problem? Depending on what it is exactly, it may or may not be new. Thanks!

**Comment by darthvader45** [comment] 2017-09-17 01:39
For me, the water doesn't show in the model all the time.  Especially in l-shaped tanks made from three normal ones.  Plus, when adding water, it should update all connected tanks instead of one at a time.

**Comment by bcrotty** [comment] 2017-09-17 01:40
I can't see the visual representation of how full the tank is. WAILA / functionality works fine.

**Comment by bcrotty** [comment] 2017-09-17 01:45
Just got a stat increase, so nevermind on that.

**Comment by CodesCubesAndCrashes** [comment] 2017-09-17 02:56
Gotcha. I confess I must have been tuning out that graphical error, since irrigation wasn't functional yet. Oops. 

Yes please, if either of you makes a new issue for that, cool. Please include the versions and pack details again. Otherwise I'll write it up myself. 

I think the issue in the OP here can be closed. Thanks again! :)

**Closed** 2017-09-17 02:57 UTC
Labels: bug, complete
