### ISSUE TITLE
Stat increase confusion

### ISSUE THREAD

**Issue by Chinthor** [AgriCraft/AgriCraft#1069] opened 2017-09-01 11:03 UTC
Not sure what should be happening vs what is happening. This config option...

  # Set to true to enable hardcore mode for stat increasing: 1 parent: 3/4 decrement, 1/4 nothing.
    #  2 parents: 2/4 decrement, 1/4 nothing, 1/4 increment.
    #  3 parents: 1/4 decrement, 1/2 nothing, 1/4 increment.
    #  4 parents: 1/4 decrement, 1/4 nothing, 1/2 increment. [default: false]
    B:"Hardcore stats"=false

Means that stats should always increase on crossbreed or stay the same, right? I'm getting a lot of random stat decreases across all stats when crossbreeding. I'm not getting many useless clones. I'm getting tons of results where all stats are lower, some are lower and some are unchanged, or one is higher and the others are lower. I usually have 4 parents in + pattern. So what gives? Is there a mechanic I'm just not understanding in 10.0-a19 ?

**Comment by CodesCubesAndCrashes** [comment] 2017-09-01 16:10
Hi! I can help with some of that. First, you'll find more information over at issue #1055 and #962. (Or the duplicates at 1036, 1028, and 977.) There's a bug with the `otherCropsAffectStatsNegatively` config that calculates the effect incorrectly. It sounds like you might be suffering from that, in which case for now you can set the Negatively config to false. 

That bug has been fixed, although a21 hasn't been released yet. Version a20 is out, and I recommend updating anyhow. 

Lastly, I can explain some of the mechanics involved here. It sounds like you've set Hardcore stats to false, but please correct me if I'm wrong. And what do you mean by "...getting many useless clones"?
* If you have Crop Stat Divisor (see below) set to >1, then the child of a mutation will reduce their starting stats before calculating any stat increases. The default Divisor is 2 for balance reasons, but you can use 1 if you prefer. If you were to set up a cross crop between four identical plants to get a Spread type crossover (instead of a Mutation type), then you should see that the stats don't get decreased. 
* Each stat gets handled separately, so not all of them will get an increase, or by the same amount. 
* Specifically, when you have normal (not hardcore) stat mode, then a stat has a chance to increase by an amount from zero (inclusive) to the number of parents (exclusive). If you have four mature and valid parent plants surrounding the cross crop, then each stat will randomly be independently raised by 0, 1, 2, or 3. 
```
    # On a mutation the stats on the crop will be divided by this number. [range: 1 ~ 3, default: 2]
    I:"Crop Stat Divisor"=2
```
Hopefully this answers your questions about "what gives"? If I misunderstood or if I didn't explain something very well, let me know. :) And if this is not a new bug, then you can also close this issue. Thank you!

**Comment by darthvader45** [comment] 2017-09-01 16:58
Thanks for the bugfix, I may actually take a crack at that new alpha.

**Comment by CodesCubesAndCrashes** [comment] 2017-09-01 17:27
@darthvader45 You're welcome! Cool. And hopefully they'll release the newest fixes soon too. :)

**Comment by darthvader45** [comment] 2017-09-01 17:33
It seems a20 isn't out either.  Is it being approved, or did you decide to skip to a21?  Just so I know, will it eventually reach a point where betas will be released?

**Comment by CodesCubesAndCrashes** [comment] 2017-09-01 18:23
@darthvader45 On a suspicion I was just looking that up on CurseForge. :expressionless: I confess that I assumed a20 had been uploaded, since the version number [got bumped a month ago](https://github.com/AgriCraft/AgriCraft/commit/11d2e0d8fc886539b7c3a0c3600bfc34e00a2876). Sorry to you and @Chinthor for the wrong advice! 

As an alternative, I'm going to try a thing out: I've generated the re-obfuscated jar for the current master branch of AgriCraft, and released it down below. I tested the jar outside of the dev environment with just the minimum mods, and it loaded a fresh save fine. If anyone wants to try it out, go ahead! I recommend having backups, of course. And please let me know how it turns out.

### [Unofficial Placeholder: the unreleased AgriCraft a20, plus additional master commits](https://github.com/CodesCubesAndCrashes/AgriCraft/releases/tag/v2.0.0-0.11.0-a20%2Bdfd1cc7%2B05eeffd%2Bce6e377)

**Comment by darthvader45** [comment] 2017-09-01 20:34
@CodesCubesAndCrashes Seems that alpha 20 you posted doesn't have the sprinkler fixes, as the sprinkler receives water and produces particles, yet doesn't hydrate farmland at ALL.  Not above, not on the same level, not even below.

**Comment by CodesCubesAndCrashes** [comment] 2017-09-01 21:02
There are no fixes for the sprinkler included currently. My sprinkler update patch is not accepted, so it's not in the master branch, so it's not in this jar. It's a large set of changes that would take time to verify, and Ryan has been been busy.

I could look into making a *really* unofficial branch and jar, but no promises. I also don't want to step on Ryan or @InfinityRaider's toes. This isn't my mod, I just contribute fixes when I can.

**Comment by darthvader45** [comment] 2017-09-01 21:06
Okay, hope this gets ironed out soon.

**Comment by Chinthor** [comment] 2017-09-01 21:46
Hi. Chinthor here again. Thanks a bunch. You have it exactly right. I am working with 4 identical mature parents in a + arrangement. In many cases, I know for certain they are identical. When I finally got an improved seed, I allowed it to spread repeatedly and used only those clones for further breeding. Yet still getting child results where one or more stats are reduced. For the time being, I'll turn off the "non-parent = negative results" feature, since I never have foreign plants in the breeding area anyway. I'll leave the mutation divisor @ 2. Makes it worth my while to use 10/10/10's as breeding parents. Looking forward to the various bug fixes in the upcoming versions and will test the next few myself. Thanks again!

**Comment by darthvader45** [comment] 2017-09-01 22:03
@Chinthor Awesome, man, pass the link to the next version you download along to me, as I also wish to test the next few updates.  Hopefully that sprinkler fix is implemented soon, I need my sprinklers.

**Comment by Chinthor** [comment] 2017-09-03 14:01
Doing some testing on the a20 you linked to above. Crossbreeding and stat increases seem back to normal.  One thing I'm not sure is working yet. Using a 10/10/10 parent to stat increase the child. As in: crossbreed beets and wheat to get sugarcane seeds, then cross the sugarcane with 10/10/10 wheat to raise sugarcane stats faster.

At the moment, I'm doing exactly that in a + pattern. A pair of perfect 10 wheat grouped with a pair of less-than-perfect sugarcane. So far, only getting weeds and VERY small gains on the sugarcane children. As if I'm only crossbreeding the two sugarcane and the wheat is not involved.

Of course, we cannot ignore the fact that the RNG hates me. But I'd like your thoughts.

Cheers

**Comment by darthvader45** [comment] 2017-09-03 15:00
It seems they are applying the extra growth ticks, as weeds grow faster.  I'm gonna need to hope this gets fixed and eventually pushed to 1.11.2, as my medieval city could certainly benefit from this.

**Comment by CodesCubesAndCrashes** [comment] 2017-09-03 19:31
@Chinthor Things: 
**1a)** How are you crossing sugarcane with wheat to raise the *sugercane* stats? Do you have any non-default mutation JSONs? The normal files don't have a cross for wheat plus sugarcane. In which case the only thing that can happen is either plant spreading onto the cross crop. Basically, what you describe sounds like it's working as designed. 

**2)** If you want to raise the stats the fastest, then make a + where all four parents are all mature and the same of best stats for that plant. Otherwise the new stats will start out reduced somehow before the stat increase is added on.

**3)** You should also sometimes be getting 10/10/10 wheat plants in the center of the +. Is that correct?

**4)** FYI, immature plants count as non-parents, and so can affect the stats negatively if that config is enabled. I'm not sure though if you still have it off or it's turned back on again.

**5)** If your mutation divisor is set to 2, then the child of the mutation can have at best 5/5/5, prior to any stat increases. So once they're 8 or more, you can't hope to do better by starting with a mutation. 

**6)** For the sprinklers, the hydrating and growth ticks are done together, and don't get separated. Currently, all the sprinklers in the world are irrigating the same cuboid located at `(0, 0, 0)`. Until a patch gets included, you can't use the sprinklers. (Except, technically, at the world origin.)

**Comment by Chinthor** [comment] 2017-09-03 19:47
Good to know about the sprinklers, thanks. 

As to wheat and sugarcane, the mutation recipe for sugarcane seeds is wheat crossed with beets, cross crops on sand. The config for stat raising states that valid stat-raisers are identical crops and parent crops. Wheat is a parent, so crossing 2x perfect 10 wheat with 2x 3/3/3 sugarcane on a sand cross crop should (on average) produce sugarcane with stats of 5-7. No wheat can spawn because it is on sand. Instead, I'm getting a lot of weeds and sugarcane at 3/3/4. Makes me think the wheat is not interacting with the child being produced. I would probably get the same results with only the sugarcane pair and better results with a 4x sugarcane (+). Can anyone confirm?

**Comment by CodesCubesAndCrashes** [comment] 2017-09-03 20:42
**1)** Sometimes I forget that sugarcane only grows on sand. My apology! Wheat can't grow on that, of course.

**2)** Clarification: the valid stat raising plants config is non-functional. There's several config options that are like that. I know, there's no indications about that. :-/ Don't know what the devs would rather do about that currently.

**3)** So, unless you added one, there is no mutation between wheat and sugarcane. So those plants can't combine together to make an offspring with better stats. What JSONs are in your config folder is what is possible. JEI should display the information visually.

**4)** Sounds like "affect stats negatively" is disabled? In which case, **confirmed** you would get the same results with just the two sugarcanes. 

**5)** Four sugarcane would be your best bet, **confirmed**.

**Comment by Chinthor** [comment] 2017-09-03 21:16
Hmmm. Good to know, but a major bummer. 

Using the parents to up the stats of the child after mutation used to work. I really liked the mechanic of breeding up the basic crops that have no mutation recipe and using them to first breed and then refine the next generation. Then repeat. If you are smart, this makes everything in the mutation recipe list a lot easier to bring to perfect 10. But only if you get strategic and methodical about it. Refine the wheat, beets, potatoes, and carrots first. Sugarcane next, because it is used in most so many others. 

If I'm understanding you, seems like now, a 5/5/5 child of perfect 10 parents is the best you can do and then pair up the children to raise them higher.

If that's the case, so be it. But I wish that config was still valid.

**Comment by CodesCubesAndCrashes** [comment] 2017-09-03 23:30
You've described the current best strategy, as far as I've determined, yup.

Just checking on your phrasing, the code that used to do that has been entirely replaced. The stat calculation has been refactored. It's not simply disabled. Mm, looks like it happened around the time of commit e7c4f0e. 

It very well might get recreated again, but I'm sorry, it's not something that can be simply tweaked.

**Comment by CodesCubesAndCrashes** [comment] 2017-09-21 02:50
@Chinthor @darthvader45 
Hi! I've uploaded a preview of the a20 release, which contains the fix for this stat increase problem. If you get a chance to try it out, let me know. Any feedback will be great. :)

https://github.com/AgriCraft/AgriCraft/releases/tag/v2.0.0a20

**Comment by darthvader45** [comment] 2017-09-21 14:58
Works great, still cannot wait for the merging of the irrigation fix, whenever that happens.

**Closed** 2017-10-28 02:34 UTC
Labels: bug, complete, release-a21
