### ISSUE TITLE
Iron nuggets hijacking recipe and not working in crafting

### ISSUE THREAD

**Issue by Liiw** [AgriCraft/AgriCraft#939] opened 2017-05-10 20:15 UTC
Hello!

I'm using Agricraft on a 1.10.2 Spongeforge server. I also have Unidict installed for unifying ore processing. I am experiencing an issue with iron nuggets from AgriCraft. Whenever I try to craft iron nuggets, I am forcefully given Agricraft nuggets even though before taking them out of the output slot, nuggets from Immersive Engineering are displayed. When trying to use Agricraft nuggets in any of the recipes, I am unable to take the crafting result from the right slot. I even tried to forcefully remove the iron nugget recipe and adding one that provides nuggets from Immersive Engineering. Only workaround for now seems to be using the nugget cast from Tinkers Construct.

**Comment by InfinityRaider** [comment] 2017-05-10 20:53
Seems like a server/client desync for the iron nugget recipe

**Comment by Liiw** [comment] 2017-05-11 03:53
Can confirm, loaded up a test SP world and tried forming an ingot from Agricraft nuggets- it worked. I also tried creating iron nuggets from an ingot and was given Immersive Engineering nuggets. I then crafted an OpenComputers cable using Agricraft nuggets and it also worked. How could this issue be fixed?

**Comment by tyler489** [comment] 2017-05-14 16:01
Its a spogeforge issue.

**Comment by RlonRyan** [comment] 2017-05-14 17:17
This is a spongeforge issue?

**Comment by Liiw** [comment] 2017-05-14 18:24
Based on the fact that this does not happen on a SP world, it would seem so. It will take me some time, but I think it's possible to test SMP. I will report my findings as soon as possible.

**Comment by TokkenGmr** [comment] 2017-05-14 22:21
I have the same issue on server I get agricraft nuggets that I can do nothing with. Single player everything works as expected. However I do not use spongecraft

**Comment by tyler489** [comment] 2017-05-14 22:48
Yeah its a spongeforge thing although i dont remeber why ...

**Comment by InfinityRaider** [comment] 2017-05-16 20:27
I think if i remember correctly that this is/was the case, if other nuggets were already detected agricraft did not add any.

**Comment by DeadSix27** [comment] 2017-06-11 19:44
I just encountered this issue, is there a fix yet? E.g forcing substatrum nuggets to be the main one in Unidict or something?

**Comment by andrewminer** [comment] 2017-09-03 23:56
Obviously this has been discussed, but I'm also having this problem in multiplayer worlds.  I'm on Minecraft 1.10.2 using `agricraft-2.0.0-0.10.0-a19.jar` with the modpack [listed here](http://github.com/andrewminer/quiet-countryside)

**Comment by Liiw** [comment] 2017-09-06 15:22
@andrewminer Just a quick question. Do you have SpongeForge installed on the server?

**Comment by andrewminer** [comment] 2017-09-06 15:41
@Liiw — No, I don't have SpongeForge on my server.

**Comment by sigmasoldi3r** [comment] 2017-09-09 16:09
I have the same issue, cannot use nuggets to craft OpenComputers things and cannot cast them in Tinker's Construct.
I'm using `agricraft-2.0.0-0.10.0-a19.jar` and `forge1.10.2-12.18.3.2185`

A list of mods:

- AbyssalCraft-1.10.2-1.9.4-pre-4.jar

- Advanced-Machines-60.0.4.jar
- agricraft-2.0.0-0.10.0-a19.jar
- ArchitectureCraft-1.7.0-mc1.10.2.jar
- bdlib-1.12.3.22-mc1.10.2.jar
- BiblioCraft[v2.2.4][MC1.10.2].jar
- Bloodmoon-MC1.10.2-1.5.1.jar
- Chameleon-1.10.2-2.3.0.jar
- CodeChickenLib-1.10.2-2.5.9.283-universal.jar
- Currency-1.10.2-1.4.3-Beta.jar
- CustomMainMenu-MC1.10.2-2.0.5.jar
- forestry_1.10.2-5.2.17.388.jar
- ForgeMultipart-1.10.2-2.0.0.38-universal.jar
- generators-0.9.20.23-mc1.10.2.jar
- industrialcraft-2-2.6.252-ex110.jar
- infinitylib-0.11.0.jar
- jei_1.10.2-3.14.7.419.jar
- JustEnoughResources-1.10.2-0.5.8.98.jar
- Mantle-1.10.2-1.1.5.jar
- MrTJPCore-1.10.2-2.0.1.20-universal.jar
- OpenComputers-MC1.10.2-1.6.2.7.jar
- OreDictionaryConverter-1.9.1.jar
- PackingTape-1.10.2-0.6.0.jar
- ProjectRed-1.10.2-4.8.4.49-Base.jar
- ProjectRed-1.10.2-4.8.4.49-fabrication.jar
- ProjectRed-1.10.2-4.8.4.49-integration.jar
- ProjectRed-1.10.2-4.8.4.49-lighting.jar
- ProjectRed-1.10.2-4.8.4.49-mechanical.jar
- ProjectRed-1.10.2-4.8.4.49-world.jar
- redstonepaste-mc1.9.4-1.7.4.jar
- signpost-1.10.2-1.05.2.jar
- Souls-1.10.2-1.1.3.jar
- StorageBoats-1.7.jar
- StorageDrawers-1.10.2-3.7.9.jar
- TConstruct-1.10.2-2.6.5.jar
- teletoro-1.10.2-20.1.jar
- thutcore-3.19.1.jar
- thuttech-4.0.12.jar
- ToughAsNails-1.9.4-1.1.1.jar
- WanionLib-1.10.2-1.3.jar
- Waystones_1.10.2-2.0.13.jar

**Comment by xAlicatt** [comment] 2017-10-04 06:04
It's really frustrating that this is being dismissed as "just a spongeforge issue" when there are people here who have stated they do not have spongeforge and it's happening to them too. 

Is there any fix or workaround for this that doesn't involve having to pour nugget by nugget from a smeltery faucet??

**Comment by DeadSix27** [comment] 2017-10-04 08:25
@xAlicatt Restarting, the game + server, that fixed it until it ..  appeared again, but I moved to 1.12.2 at this point.. so All i can do is hope for it to be fixed in the 1.12 release

**Comment by xAlicatt** [comment] 2017-10-04 08:29
@DeadSix27 I think moving to 1.12 is very premature, but to each his/her own I spose. 

I've tried restarting, i've tried using auto-ore dictionary converter and forge lexicon to force nuggets to the preferred mod. Nothing works. Agricraft forces its borked ingots onto you whether you like it or not. The only workaround i have found is pouring nuggets one by one through tinkers.

**Comment by DeadSix27** [comment] 2017-10-04 09:36
@xAlicatt I had massive performance issues on 1.10, not sure what mod(-combination) caused it.. but ye.. everything works surprisingly smoother in 1.12 for me.. while I do miss EnderIO and hope they ditch 1.11 for 1.12 like a few others do.. I relied on EnderIO so much in the past time to try without :)

**Comment by CodesCubesAndCrashes** [comment] 2017-10-15 11:15
# Update and fix

The cause of this bug was that `OreDictionary#registerOre` was being called in a client side only method, meaning that AgriCraft nuggets would be missing from the ore dictionary of a dedicated server. The recipes would show up correctly in the GUI, and they would work fine in single player, but the server would veto any attempts to use them. 

The bug had been hidden because the override method in AgriCraft's code didn't have the client side only label. But since the original has the `@SideOnly(Side.CLIENT)` annotation, then the override will also receive the effect. 

I've [committed a patch](https://github.com/AgriCraft/AgriCraft/commit/31216eb7d4ee02cc07f393e626e431b669c8a401) for this, that makes sure the ore dictionary registration gets called on the server too. I've also added a [few other commits](https://github.com/AgriCraft/AgriCraft/search?utf8=%E2%9C%93&q=committer-date%3A2017-10-15&type=Commits) that improve or fix nugget related things.

I tested them out by putting the re-obfuscated jar into a fresh copy of the [FTB Beyond (v1.11.0, MC 1.10.2) modpack](https://www.feed-the-beast.com/projects/ftb-beyond/files/2468604). First in single player, and then in a local dedicated server. 
* I crafted ingots using only AgriCraft nuggets and then also in a mixture of other ones. 
* I repeated that for all of the materials, except for Osmium since I didn't have Mekanism installed.
* I looked in JEI at the usage recipes for the AgriCraft nuggets, and I didn't see any obvious weirdness. 
* I crafted some parts from OpenComputers using AgriCraft's iron nuggets. 

If anyone can describe their bug experiences more specifically, then I can test those too. I looked at the reports here, and also in the other issues (like 137, 773, 783, 1043, and 1066), but more specific examples are welcome. 

## Screenshots from testing the patch
![agricraft nuggets 01](https://user-images.githubusercontent.com/28678248/31584076-de648a82-b15b-11e7-8223-9892690f2da9.png)
![agricraft nuggets 02](https://user-images.githubusercontent.com/28678248/31584077-de7c28d6-b15b-11e7-87a8-2806149a391e.png)

**Comment by sigmasoldi3r** [comment] 2017-10-15 14:04
I'll test it ASAP

**Comment by TokkenGmr** [comment] 2017-10-15 14:59
Will take a look later today

**Comment by CodesCubesAndCrashes** [comment] 2017-10-16 09:53
@sigmasoldi3r Which part is it stuck on? A fresh install sometimes trips me up. For example, I tend to forget to do `git submodule init`. Are you trying to get it into an IDE, or just do `gradlew reobfJar`?

**Closed** 2017-10-28 02:22 UTC
Labels: bug, complete, release-a21
