### ISSUE TITLE
Server crash when placing an Extra Utilities 2 Fluid Transfer Node on an AgriCraft tank

### ISSUE THREAD

**Issue by localzuk** [AgriCraft/AgriCraft#1169] opened 2018-07-15 13:48 UTC
When a player places a Fluid Transfer Node from Extra Utilities 2 on an AgriCraft tank, it causes a full crash in multiplayer.

Relevant versions:

Minecraft 1.12.2
AgriCraft - agricraft-2.12.0-1.12.0-a5
Extra Utilities 2 - extrautils2-1.12-1.7.6

Crash Log:

`Description: Ticking block entity

java.lang.NoSuchMethodError: com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.setFluidAmount(I)V
    at com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.drain(TileEntityTank.java:109)
    at com.rwtema.extrautils2.transfernodes.TransferNodeFluid.processBuffer(TransferNodeFluid.java:81)
    at com.rwtema.extrautils2.transfernodes.TransferNodeFluid.processBuffer(TransferNodeFluid.java:31)
    at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151)
    at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:68)
    at net.minecraft.world.World.func_72939_s(World.java:1832)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)`

Full Crashlog - https://pastebin.com/JLLuFA3E

Relevant bit from latest.log:

`[13:53:18] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.setFluidAmount(I)V
	at com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.drain(TileEntityTank.java:109) ~[TileEntityTank.class:?]
	at com.rwtema.extrautils2.transfernodes.TransferNodeFluid.processBuffer(TransferNodeFluid.java:81) ~[TransferNodeFluid.class:?]
	at com.rwtema.extrautils2.transfernodes.TransferNodeFluid.processBuffer(TransferNodeFluid.java:31) ~[TransferNodeFluid.class:?]
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151) ~[TransferNodeBase.class:?]
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:68) ~[TileTransferHolder.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
[13:53:18] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Minecraft\Curse\Edugeek Build Pack Server\.\crash-reports\crash-2018-07-15_13.53.18-server.txt`

**Comment by opl-** [comment] 2018-07-16 16:35
Duplicate of #1167

**Closed** 2018-07-16 22:18 UTC
Labels: duplicate
