### ISSUE TITLE
(Minor) Fences visually connect to crops

### ISSUE THREAD

**Issue by Crowfooted** [AgriCraft/AgriCraft#1153] opened 2018-06-30 15:07 UTC
Simple and minor - vanilla fences (and other fences) connect visually to neighbouring Agricraft crops.

**Comment by darthvader45** [comment] 2018-06-30 15:18
Seems like a simple code change to prevent this from happening.  Thanks for
the report.

Golden rule in Minecraft: Never dig straight down.

**Comment by darthvader45** [comment] 2018-06-30 15:19
I'm sure they'll fix this quickly.

Golden rule in Minecraft: Never dig straight down.

**Comment by opl-** [comment] 2018-07-16 16:38
Duplicate of #1123

**Closed** 2018-07-16 22:18 UTC
Labels: bug, duplicate
