### ISSUE TITLE
Sprinklers don't work on multiplayer server

### ISSUE THREAD

**Issue by tyggna** [AgriCraft/AgriCraft#1162] opened 2018-07-07 15:03 UTC
This is a fresh save, server runs forge-1.12.2-14.23.4.2705 and minecraft 1.12.2
Agricraft is version: 2-12.0-1.12.0-a4

Channels/water tank fill off of (alpha) buildcraft 7.99.17 pump or just bucketing it in.  Water tank is multiblock.  Sprinkler attached to full irrigation channel, no animation, no particle effects, no perceived increase on crop growth speed.

After letting it run, on a new user logging in, the server crashes with the following traceback:

> 
> [16:22:08] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
> net.minecraft.util.ReportedException: Ticking block entity
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
> Caused by: java.lang.AssertionError: With 16018mb of total fluid, somehow consumed -2mb, which should be impossible!
>         at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.acceptFluid(TileEntityChannel.java:228) ~[TileEntityChannel.class:?]
>         at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.pushToComponent(TileEntityChannel.java:338) ~[TileEntityChannel.class:?]
>         at com.infinityraider.agricraft.tiles.irrigation.TileEntityChannel.func_73660_a(TileEntityChannel.java:272) ~[TileEntityChannel.class:?]
>         at com.infinityraider.agricraft.tiles.irrigation.TileEntityTank.func_73660_a(TileEntityTank.java:57) ~[TileEntityTank.class:?]
>         at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
>         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
>         ... 4 more
> ****

**Comment by RlonRyan** [comment] 2018-07-10 23:45
This is a duplicate of another issue that has been fixed in the latest release.

**Closed by RlonRyan** 2018-07-10 23:45 UTC
Labels: duplicate

**Comment by tyggna** [comment] 2018-07-11 00:15
can you link the latest release, since it's not on curseforge?

**Comment by RlonRyan** [comment] 2018-07-11 01:16
https://minecraft.curseforge.com/projects/agricraft/files/2581277

**Comment by tyggna** [comment] 2018-07-11 03:04
Hey, thanks for all the great work you're doing!
