### ISSUE TITLE
Crops no Spread

### ISSUE THREAD

**Issue by darudeg** [AgriCraft/AgriCraft#1217] opened 2019-03-09 19:16 UTC
## Quick description

Crops are not spreading
## Related issues and searches

* https://github.com/AgriCraft/AgriCraft/issues?q=is%3Aissue%20EXAMPLE

## Mods and versions used

* Minecraft:1.12.2
* AgriCraft:2.12.0-1.12.0-a6
* InfinityLib:1.12.0
* [List the other required mods here]

## Steps to replicate the issue

1. Loaded up Project ozone 3
2. Placed a Crop in a crop stick
3. Right-clicked with watering can for ages on crop
4. expected spread, no spread

## Expectations and explanations

I think spread and mutating should have happened. I wanna grow 101010 crops boi.
## Your environment

* How are you playing?
  * Operating System: Windows
  * Launcher: Twitch/Minecraft
  * Modpack: Project Ozone 3
* What kind of server:
  * [ ] Singleplayer
  * [ ] Multiplayer
  * [X] Lan
* Game Modes:
  * [X ] Survival
  * [ ] Creative
* Save File:
  * [ ] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc

* https://gist.github.com/
* https://paste.ee/
* https://duckduckgo.com/?q=pastebin+alternatives
* Upload them somewhere, and then replace these links.

**Comment by kmoxcey** [comment] 2019-04-01 16:56
I'm using same version of Agricraft & Infinitylib on a single player world. I've tried both existing & new saves. It seems like the plants will not spread to cross crops, but will spread to a single set of crops. I haven't played long enough to see how it affects stat gain or if crossbreeding works.

**Comment by kmoxcey** [comment] 2019-04-01 19:27
I believe I've found the issue:

In agricraft/tiles/TileEntityCrop.java, the function spread() has an incorrect condition. 

`if (!crop.isCrossCrop()) {           // This should be if (crop.isCrossCrop())
     crop.setSeed(this.seed);
     return true;
}`

**Comment by Dasin6** [comment] 2019-05-24 10:43
agricraft 2.12.0 a6 on minecraft 1.12.2
my own made modpack but 

after altering configs to make agricraft crops spread faster crops stop spreading onto double cropsticks after a restart

all configurations that were changed were no more then what one could do in the minecraft in setting/mods/agricraft

at first i thought it was caused by disabling agricraft irrigation

**Comment by InfinityRaider** [comment] 2021-01-22 22:05
Closing since we are moving to 1.16.

**Closed by InfinityRaider** 2021-01-22 22:05 UTC
Labels: 1.12.2-unfixed, bug
