### ISSUE TITLE
Irrigation channels wont craft

### ISSUE THREAD

**Issue by Dragonracer73** [AgriCraft/AgriCraft#891] opened 2017-03-29 01:20 UTC
playing on a small put together pack and using agricraft for the first time in 1.10.2 but the irrigation channels will not craft in multiplayer. Thought it might be a conflict with another recipe but Jei is not showing it in planks use. I have a zip here with the mod list and screenshots. screenshot one is of the analog crafter from extra utillities, while screen 2 which does show the finished channels, will not allow me to pull them from the crafting table. This problem has occured with other players, so it is not my player data related.
[Agricraft bug modlist and screenshots.zip](https://github.com/InfinityRaider/AgriCraft/files/877490/Agricraft.bug.modlist.and.screenshots.zip)

also as of the last week of march, same version of the mod, sprinklers do not seem to be working, at all.

**Comment by tolly7654** [comment] 2017-04-01 19:17
We are also having this issue on our server. We looked through configs and tried with and without sponge installed on our server, and they remain uncraftable. The conflict mod in FTB Beyond also doesn't fix anything related to conflicting recipes.

**Comment by RlonRyan** [comment] 2017-04-05 16:01
Duplicate of #724

**Closed by RlonRyan** 2017-04-05 16:02 UTC
