### ISSUE TITLE
Crop spreading / stat increase wont work ?

### ISSUE THREAD

**Issue by Darianna77** [AgriCraft/AgriCraft#1055] opened 2017-08-01 11:17 UTC
Hello....since weeks ill try to increase the stats from my plants but it isnt possible for me :/
Is there something change to 1.7.10 ?

In 1,7.10 i have made a row with 9 or 10 cropsticks....in the first i plant a seed....and the other all double cropsticks...
have tried it....sometime the plant spreaded 1 more time....but then it stops....have wait 2 or 3 minecraft weaks...nothing
when i plant one crop...then an double cropstick....then another crop. Sometime it spreads in the middle thing...but i get never any stat increase...
When i made an single cropsticks...the crops spread...but wont growth..

So i have tried to change the spreadrate for wheat on 0.5 ...than it spreads.....but the stat wont increase...
have change the config for single spread stat increase to ture also....but all what i get after 10 spreads is 1-1-1

so please help me...whats wrong...what are the difference to 1.7.10 ?
after playing nearly one rl month i really will have better crops :/

**Comment by MBelhardi** [comment] 2017-08-01 23:10
I can confirm, that there must be something wrong with the spreading values.

Unfortunately, I must say, that spreading the seeds takes much too long. If my thought is correct, and the spreading will be calculated from the general spreading chance and the spreading chance of the individual plant, then that is no wonder. The default value, of the config file, for the spreading chance is **0.15**, and the spreading chance of most plants is **0.1**, which results in a total-spreading chance of **0.15 x 0.1 = 0.015**. At least I think, that this is how the spreading chance will be calculated, otherwise I can't actually explain, why the spreading needs so long.

config-value:
```
    # The base chance for a crossover to occur during any given tick. Setting this 95% is of questionable morality. [range: 0.05 ~ 0.95, default: 0.15]
    S:"Crossover Chance"=0.15

```
plant-value: (for example wheat)
`  "spread_chance": 0.1,
`  

I had to change the config-value to **0.55** and the plant-value to **0.3** (in **total 0.165**) to get a reasonable spreading time. (while I'm using the agricraft irrigation system) I don't want to know, how long it will take, without the irrigation system.
With these changes it took me almost 6 hours to get 1 10/10/10 Seed. (weed was disabled)

Also, sometimes plants will spread to another crop, even though it's not a double crop

**Comment by cap1o** [comment] 2017-08-03 13:08
Hello !

I have got the same problem with the 1.10.2 Agricraft 2.19a on Beyond modpack.
Sprinklers seem not working and i wait 3H IRL to get nothing more on plant stat.
I have got only 1/1/1 and weed.
May i done wrong and i don't know about config files how to fix that.

I play on a host server alone.
If someone can help me because i need agricraft for intense farming.
Thanks

**Comment by Redhandjane** [comment] 2017-08-11 01:34
I am unable to breed better plants as well in Minecraft 1.10.2 with Agricraft a19. I have my wheat plants planted in a cross shape, with a double crop stick in the center. All plants coming out of the center are 1/1/1

**Comment by CodesCubesAndCrashes** [comment] 2017-09-01 15:15
@MBelhardi Wanted to follow up about your math. You're right, and it's actually worse than that. When a cross-crop gets an update tick it rolls for: 
* Global crossOverChance = 0.15
* Spread Strategy Chance = 0.8 (versus Mutation Strategy on the other 0.2)
* Plant's spread_chance = 0.1

That comes out to an approximate (because floating numbers) probability of **0.012**. 

If the `Fertilizer Mutations` option is off, then right now you can't speed things up. You have to rely on vanilla random ticks. Based on the [wiki](https://minecraft.gamepedia.com/Tick#Block_tick), a block gets a tick on average every 68.2667 seconds. Divide that by the total spread probability, and you get 5688.89 seconds between successful spreads. Which is **94.81 minutes**. This was brought up previously in issue #958, where @mrlamb did the same math as you. 

I don't have an intuitive answer for how to solve this in a simple way. 

#### 1)
One option would be to default crossOverChance to a high value, I would even say 1.0. That way the default effective spread chance would be 80% of the JSON value. The math for that would be 68.266/0.08/60 = **14.22 minutes**. Which is still a longish but fair amount. If a pack maker wants things to be hardcore, they can turn it down to a lower chance.

There's a catch though! If `Fertilizer Mutations` are enabled, then you can be really quick. With all defaults it would take you ~83 bonemeal to trigger the crossover spread. Expensive maybe, but not a long time. And if you also set crossOverChance to 1.0, then it would take only ~12.5 bonemeal. Seems too easy. I think it took me on average about 7 generations to get from 1/1/1 to 10/10/10. A couple minutes per generation to bonemeal everything and then reset the crops with the new seeds. So only about 15 minutes in total. 

#### 2)
Another option would be to skip the spread chance check in the Spread Strategy, on the assumption that if you got that far, it's already a low enough. (Default: 0.12) But I think that wouldn't be good, since it would mean all plants have the same chance to spread and grow on cross crops. The JSON spread_chance would still be used for spreading to regular crop sticks. But you don't get any stat changes from that kind of spreading.

#### 3)
Make plants change stats when they spread to adjacent regular crops. This kind of spreading is more likely already. (But also it has probability problems of its own. >.<) Then cross crop spreading wouldn't matter as much. Possibly could even remove it, to make things less complicated.

#### The bottom lines are: 
* **Game balance is hard.** There's a lot of values to tweak, and different mechanics to consider.
* Option 1 can be done right now by anyone, like MBelhardi showed. I would even leave the JSONS alone.

**Comment by cap1o** [comment] 2017-09-02 09:12
So i don't understand what shloud i do to get it more quicker for mutation and Spread ? 
I paste you a part of the config file.
I would enjoy to appreciate Agricraft, but if the difficulty it's only base on the time to wait, i would make stats from **1 to 10** in **2 / 3 hours** max.
I'm French and very bad with math lol, i understand well english but not the stat value and setup that.
If it's an issue, tell me and i remove the mod for the 1.10.2 MC version.
Thank you for your help.
```
farming {
    # On a mutation the stats on the crop will be divided by this number. [range: 1 ~ 3, default: 2]
    I:"Crop Stat Divisor"=2

    # The base chance for a crossover to occur during any given tick. Setting this 95% is of questionable morality. [range: 0.05 ~ 0.95, default: 0.15]
    S:"Crossover Chance"=0.15

    # Set to true to disable vanilla farming, meaning you can only grow plants on crops. [default: false]
    B:"Disable Vanilla Farming"=false

    # Set to false if you wish to disable using fertilizers on a cross crop to force a mutation. [default: false]
    B:"Fertilizer Mutations"=false

    # This is a global growth rate multiplier. [range: 0.0 ~ 2.0, default: 1.0]
    S:"Growth rate multiplier"=1.0

    # Set to true to enable hardcore mode for stat increasing: 1 parent: 3/4 decrement, 1/4 nothing.
    #  2 parents: 2/4 decrement, 1/4 nothing, 1/4 increment.
    #  3 parents: 1/4 decrement, 1/2 nothing, 1/4 increment.
    #  4 parents: 1/4 decrement, 1/4 nothing, 1/2 increment. [default: false]
    B:"Hardcore stats"=false

    # Define mutation chance (0.0 means no mutations, only spreading and 1.0 means only mutations no spreading. [range: 0.0 ~ 1.0, default: 0.2]
    S:"Mutation Chance"=0.2

    # True means any crop that is not considered a valid parent will affect stat gain negatively. [default: true]
    B:"Non parent crops affect stats negatively"=true

    # Set this to true to make only mature crops drop seeds (to encourage trowel usage). [default: false]
    B:"Only mature crops drop seeds"=false

    # Set to false if you wish to disable drops from raking weeds. [default: true]
    B:"Raking weeds drops items"=true

    # Set to true to warn that vanilla farming is disabled when trying to plant vanilla plant. [default: true]
    B:"Show Disabled Vanilla Farming Warning"=true

    # Set to true to allow crops that spread from one single crop to increase stats. [default: false]
    B:"Single spread stat increase"=false

    # What are considered valid parents for stat increasing: 1 = Any. 2 = Mutation parents and identical crops. 3 = Only identical crops. [range: 1 ~ 3, default: 2]
    I:"Valid parents"=2

    # The average number of growth ticks for the weed to grow. [range: 10 ~ 50, default: 50]
    I:"Weed Growth Rate"=50

    # Set this to true to have weeds destroy the crop sticks when they are broken with weeds (to encourage rake usage). [default: false]
    B:"Weeds destroy crop sticks"=false

    # Determines if AgriCraft should completeley override grass drops with those confiured in the JSON files. [default: false]
    B:"Wipe Grass Drops"=false
```

**Comment by CodesCubesAndCrashes** [comment] 2017-09-02 20:23
@cap1o Option **1)** should do that for you. Going 1/1/1 to 10/10/10 will take both time and also some effort for moving around the best plants. It takes almost 15 minutes for a plant to spread to an empty crosscrop, and hopefully also have improved stats. It can take about 7 generations if you've got four strong parents each time. That comes out to <2 hours of waiting, plus the time and work for setting up each generation.

```JSON
##### The important values are:
    S:"Crossover Chance"=0.95                            # <-- Change this to 0.95
    B:"Fertilizer Mutations"=false                       # <-- Keep false
    B:"Hardcore stats"=false                             # <-- Keep false
    S:"Mutation Chance"=0.2                              # <-- Keep at 0.2
    B:"Non parent crops affect stats negatively"=false   # <-- Keep false, until fix released
    B:"Single spread stat increase"=false                # <-- Keep false
```

**Comment by cap1o** [comment] 2017-09-02 20:47
>  The important values are:
>     S:"Crossover Chance"=0.95                            # <-- Change this to 0.95

You mean to change :

` S:"Crossover Chance"=0.15 #<-- change to 0.95` ?

It's done !
Thank you and i will wait forward to the new release !

Thank you for your mod it's usefull !

**Comment by CodesCubesAndCrashes** [comment] 2017-09-02 20:51
@cap1o Hah, I added the comments after picking the suggested values, intending to explain what I had done. I described it the wrong way. But yup, you got the key step. Also, it's not my mod. However you are very welcome! Glad to help.

**Comment by cap1o** [comment] 2017-09-02 20:53
No problem then i can explain it to FTB Forum and French Players on my server thank you for your help !

**Comment by CodesCubesAndCrashes** [comment] 2017-09-21 02:50
@Darianna77 @cap1o @Redhandjane 
Hi! I've uploaded a preview of the a20 release, which contains the fix for this stat increase problem. If you get a chance to try it out, let me know. Any feedback will be great. :)

https://github.com/AgriCraft/AgriCraft/releases/tag/v2.0.0a20

**Closed** 2017-10-28 02:34 UTC
Labels: bug, complete, release-a21
