### ISSUE TITLE
java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES

### ISSUE THREAD

**Issue by Allalous** [AgriCraft/AgriCraft#1034] opened 2017-07-07 02:16 UTC
Hi, love your mod to almost death. I am trying to make my own modpack with your mod but in a recent update, I crash every time I try to use the crops sticks. Making them is fine, pulling them out of JEI is fine, but whenever I place them in the world I crash with this crash log every time.

https://pastebin.com/9aVaisZk

**Comment by Joshwoo70** [comment] 2017-07-07 15:37
Same error different set of mods:
[crash-2017-07-07_23.26.22-client.txt](https://github.com/AgriCraft/AgriCraft/files/1131476/crash-2017-07-07_23.26.22-client.txt)

**Comment by danellos** [comment] 2017-07-09 18:10
I have encountered the same issue with my custom modpack.
[crash-2017-07-09_13.49.52-client.txt](https://github.com/AgriCraft/AgriCraft/files/1133950/crash-2017-07-09_13.49.52-client.txt)

**Comment by KebnTheFirst** [comment] 2017-07-09 22:58
Same crash but mine involves Refined Storage
https://pastebin.com/T6tpnN6R

**Comment by xAlicatt** [comment] 2017-07-11 06:28
[https://gist.github.com/xAlicatt/53e090fadbb040356861f45b31c84bc5](url)

**Comment by CodesCubesAndCrashes** [comment] 2017-07-12 00:27
Hello everyone! Thank you for providing raw data. :)

If anyone is interested, these seem to be related to some long standing crashes that keep popping up. Reports #777, #974, #981 are some examples. The better news is that InfinityRaider and Mezz did deduce [how the crash was happening](https://github.com/InfinityRaider/InfinityLib/issues/20), even if "way" is still a mystery. It's been tricky because when the bug screws things up, it doesn't crash the game. And when the game does crash, it's probably not the fault of the block or item that's in the stack trace. 

The other complication is that this crash does not occur when testing AgriCraft alone. Neither in the debugger, nor after re-obfuscation. So some other Mod is required, but which one(s)? There's a lot of candidates. Almost all the crash reports are from very large packs.

So, I have a humble request for anyone who encounters this problem in the future. If you can, go and take 5 minutes to look at part of your full log file, and see what other error messages show up. And add a small excerpt to your report, if it looks interesting? 

Finally, if you're super awesome, feel free to recreate the crash with fewer mods enabled. Because I've been testing enabling mods individually, or in groups, and I still haven't isolated the bug yet.

Thank you in advance! I also hope you found something interesting in those links and summary. And don't forget to check what version of AgriCraft you're testing! 😁

**Comment by DinDillian** [comment] 2017-07-12 03:24
I've just gone through a modpack update for a private modpack of mine, and I was getting this issue when updating all of the mods so I went through all of them one-by-one to see which was causing the issue. It would seem that JourneyMap 1.10.2 - 5.4.9b1 (the latest beta build) is causing this crash. There may be other mods also causing this issue, but none in my modpack.

**Comment by Joshwoo70** [comment] 2017-07-12 07:02
same issue. journeymap updated to that version

**Comment by xAlicatt** [comment] 2017-07-12 07:23
Thank you @DinDillian !!

**Comment by KebnTheFirst** [comment] 2017-07-12 21:19
I was on that version of JourneyMap, I downgraded and am now running fine with no issues.

**Comment by CodesCubesAndCrashes** [comment] 2017-07-12 23:44
Yup! Tested it earlier while adding only JourneyMap, and I could reproduce the crash. Looks like there's a problem during the initial loading, before the main menu. I think JourneyMap is rendering all the blocks in order to calculate and cache the colors to use to draw them on the map. There's a null pointer exception, which leaves the tessellator is in a bad state. After that, we get the "ALREADY" exceptions. The difference later on is that JourneyMap suppresses the exceptions, to let the game finish loading. But they aren't suppressed once you're in game. 
### [Condensed log of the crash.](https://gist.github.com/CodesCubesAndCrashes/0e837e61b0eef46047c9552e49361c28)
```
[Client thread/INFO] [journeymap/]: Loading blocks and textures...
[Client thread/INFO] [journeymap/]: Existing color palette's resource packs and mod names match current loadout.
[Client thread/INFO] [journeymap/]: New color palette will be created
[Client thread/ERROR] [journeymap/]: Error calling com.infinityraider.infinitylib.render.block.BakedInfBlockModel.getQuads(IBlockState, up, 0) in BlockRenderLayer Solid (SUPPRESSED)
[Client thread/ERROR] [journeymap/]: java.lang.NullPointerException
	at com.infinityraider.agricraft.renderers.blocks.RenderCrop.renderWorldBlockStatic(RenderCrop.java:63)
	at com.infinityraider.agricraft.renderers.blocks.RenderCrop.renderWorldBlockStatic(RenderCrop.java:30)
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.createQuads(BakedInfBlockModel.java:64)
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.lambda$getQuads$1(BakedInfBlockModel.java:58)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.getQuads(BakedInfBlockModel.java:58)
	at journeymap.client.cartography.ColorHelper.getSprites(ColorHelper.java:345)
        ...
```

**Comment by Joshwoo70** [comment] 2017-07-13 02:17
reported to techbrew on his discord @techbrew-mc

**Comment by ACGaming** [comment] 2017-07-13 07:38
I'm getting this crash too but I don't have JourneyMap installed.
https://paste.ubuntu.com/25080618

**Comment by InfinityRaider** [comment] 2017-07-16 11:29
@DinDillian So agricraft + infinitylib + that version of journeymap triggers this error?

@ACGaming That's a lot mods. If you can narrow it down that would be appreciated. Optimally I'd need InfinityLib + AgriCraft + mod X which triggers this crash (similar to what DinDilian figured out with JourneyMap).

reproducing this crash in dev is the key to solving this, and so far I have not managed to reproduce it...

**Comment by DinDillian** [comment] 2017-07-16 13:52
@InfinityRaider I just tested with a new modpack using the following:

- Forge 12.18.3.2316
- Agricraft 2 a19
- InfinityLib 0.11.0
- JourneyMap 5.4.9b1
- JEI 3.14.7.420

No other mods were installed and I crashed whilst searching for "crop" in JEI search. I only got as far as typing "cr" before the crash occurred, presumably because JEI had to show the crop on screen at that point.

**Comment by Joshwoo70** [comment] 2017-07-17 02:18
Seems like the root cause of the sudden arise is due to Journeymap's beta.

**Comment by ACGaming** [comment] 2017-07-17 05:30
I will narrow it down when I get back from my vacation this weekend.

**Comment by techbrew-mc** [comment] 2017-07-17 06:34
JourneyMap tries to get the textures from a BakedModel's quads in order to derive a color.  This currently happens after mods are loaded, but before there's an active world.  I've found a few mods that don't handle this well because they're expecting an active VertexBuffer, etc.  

Perhaps that's the problem here as well.

I'm working on an alternative which will wait for the world to load, at the risk of lagging gameplay on first use.  The next 1.10.2 beta of JM will have the new approach.

**Comment by CodesCubesAndCrashes** [comment] 2017-07-17 07:08
@techbrew-mc Thanks for the update. :) Out of my own curiosity, how were the colors assigned before? And will they be cached until the client quits, or across launches too? I see that there are recent posts/tweets about the improved process, and the older ones about the palette JSON. And I *think* the bitbucket plus source is private, but I could be looking in the wrong places. Hopefully I didn't miss the answers on CF/discord/BB/theWebsite. >.< Cheers!

**Comment by InfinityRaider** [comment] 2017-07-17 11:34
@techbrew-mc normally that shouldnt be an issue, my models dont require an active vertex buffer. Most of them require tile entity data though, but they just bake a standard model if the world/tile is null.

I doubt it's only journeymap, there's something funky going on and I don't know what (because the crash also happens without journeymap present, as illustrated by @ACGaming).

**Comment by ACGaming** [comment] 2017-07-23 10:37
**UPDATE:** I got around to narrow down the issue today and after disabling tons of mods and verbose testing, I finally found the culprit (kind of): Astoundingly, it was my resource pack ([Faithful Modded Edition](http://www.f32.me)) which was causing the crashes.
AgriCraft gathers textures from the current resource pack, right? Maybe there's something wrong in that regard but I'm not sure.

**Comment by InfinityRaider** [comment] 2017-07-23 10:50
Wat

**Comment by ACGaming** [comment] 2017-07-23 13:30
[HORY SHET](https://pics.me.me/Instagram-e2a95b.png), it gets creepier with every testing session! Made a new modpack instance and got this:

[Wooden tanks](http://i.imgur.com/QYGDPCs.png)
[Borked items in JEI/NEI](http://i.imgur.com/axeZvob.png)

**Comment by InfinityRaider** [comment] 2017-07-23 13:44
something is fucked with the UV's, but that's a separate issue, is there still the "ALREADY CONSTRUCTING VERTICES" in the log? I suppose not right?

**Comment by ACGaming** [comment] 2017-07-23 13:59
Only when using OptiFine together with a resource pack. OptiFine and resource packs work fine when used seperately.

**Comment by InfinityRaider** [comment] 2017-07-23 14:07
...

I do not and never will support Optifine.
Is anyone actually having this crash without Optifine?

**Comment by ACGaming** [comment] 2017-07-23 14:24
I believe I'm the only one with this issue who hasn't installed Journey Map.

You don't have to support OptiFine but I find it very odd that this problem only occurs when you are running OptiFine together with a resource pack. OptiFine on its own (Default resource pack) runs perfectly fine. A resource pack on the other hand runs perfectly fine without OptiFine. And it only affects AgriCraft. I don't know if it can be fixed on your or OptiFine's end.

**Comment by SoraTDG** [comment] 2017-08-07 03:09
I'm Having this crash with no optifine installed there is so many threads i cant tell if anyone has found a solution too this problem, also im getting this on a custom modpack I'm making for a local server if that is is any help. here my crash report
[crash-2017-08-06_20.59.58-client.txt](https://github.com/AgriCraft/AgriCraft/files/1203780/crash-2017-08-06_20.59.58-client.txt)

**Closed** 2018-03-01 03:56 UTC
Labels: complete, other mod, wat
